Enable to specify a target file name

diff --git a/latexmk-ext b/latexmk-ext
--- a/latexmk-ext
+++ b/latexmk-ext
@@ -2,12 +2,14 @@
 
 set -eu
 
-if ! [ -r main.tex ]; then
-  echo -e "\x1b[31mCould not read file 'main.tex': Permission denied\x1b[0m"
+FILE_NAME=${1:-main.tex}
+
+if ! [ -r "$FILE_NAME" ]; then
+  echo -e "\x1b[31mCould not read file '$FILE_NAME': Permission denied\x1b[0m"
   exit 1
 fi
 
-latexmk -pvc main 2>&1 \
+latexmk -pvc "$FILE_NAME" 2>&1 \
   | sed -uE -e '/^!/!bend;s/^.*$/\x1b[30;41m&\x1b[0m/;:loop;N;/(\nNo pages of output.)|(\nOutput written)|(\n! )|(\nLatexmk:)/bend;s/\n([^\n]*$)/\n\x1b[31m\1\x1b[0m/;bloop;:end;P;D' \
   | sed -uE -e '/(^LaTeX Warning:)|(^LaTeX Font Warning:)|(^Package babel Warning:)|(^Runaway argument\?)|(^Underfull \\hbox)|(^Overfull \\hbox)|(^Underfull \\vbox)|(^Overfull \\vbox)/s/^.*$/\x1b[33m&\x1b[0m/' \
   | sed -u  -e '/^Running /s/^.*$/\x1b[0m&\x1b[0m/' \
